name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-test-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        shell: pwsh

      - name: Run tests
        run: npm test
        shell: pwsh

      - name: Build project
        run: npm run build
        shell: pwsh
